# Generated by Django 4.1.7 on 2023-03-20 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_content_alter_posts_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 13, 8, 226217, tzinfo=datetime.timezone.utc)),
        ),
    ]
