# Generated by Django 4.1.7 on 2023-03-24 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 20, 16, 1, 189778)),
        ),
    ]
