# Generated by Django 4.1.7 on 2023-03-24 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 20, 16, 47, 709349, tzinfo=datetime.timezone.utc)),
        ),
    ]
